from __future__ import annotations

# Этот файл автоматически создан backtest_strategy.py по результатам validation.
# Им можно заменить validation_hyperparameters.py, чтобы прогнать только
# лучшие найденные параметры и затем выполнить test backtest.

# Этот файл предназначен для финального test-прогона без повторной validation.
RUN_VALIDATION_BACKTEST = False
RUN_TEST_BACKTEST = True

BACKTEST_STRATEGIES = ['momentum',
 'mean_reversion',
 'ma_trend',
 'breakout',
 'ridge',
 'catboost',
 'random_forest',
 'decision_tree',
 'gru',
 'lstm',
 'transformer',
 'tcn']

VALIDATION_PARAMETER_GRIDS = {'momentum': [{'threshold_bp': 80.0,
               'max_positions': 1,
               'buy_cost_bp': 1.0,
               'sell_cost_bp': 1.0},
              {'threshold_bp': 120.0,
               'max_positions': 1,
               'buy_cost_bp': 3.0,
               'sell_cost_bp': 3.0},
              {'threshold_bp': 140.0,
               'max_positions': 1,
               'buy_cost_bp': 5.0,
               'sell_cost_bp': 5.0}],
 'mean_reversion': [{'threshold_bp': 0.0,
                     'max_positions': 50,
                     'buy_cost_bp': 1.0,
                     'sell_cost_bp': 1.0},
                    {'threshold_bp': 50.0,
                     'max_positions': 40,
                     'buy_cost_bp': 3.0,
                     'sell_cost_bp': 3.0},
                    {'threshold_bp': 100.0,
                     'max_positions': 12,
                     'buy_cost_bp': 5.0,
                     'sell_cost_bp': 5.0}],
 'ma_trend': [{'threshold_bp': 70.0,
               'max_positions': 1,
               'buy_cost_bp': 1.0,
               'sell_cost_bp': 1.0},
              {'threshold_bp': 80.0,
               'max_positions': 1,
               'buy_cost_bp': 3.0,
               'sell_cost_bp': 3.0},
              {'threshold_bp': 120.0,
               'max_positions': 1,
               'buy_cost_bp': 5.0,
               'sell_cost_bp': 5.0}],
 'breakout': [{'threshold_bp': 70.0,
               'max_positions': 1,
               'buy_cost_bp': 1.0,
               'sell_cost_bp': 1.0},
              {'threshold_bp': 80.0,
               'max_positions': 1,
               'buy_cost_bp': 3.0,
               'sell_cost_bp': 3.0},
              {'threshold_bp': 120.0,
               'max_positions': 1,
               'buy_cost_bp': 5.0,
               'sell_cost_bp': 5.0}],
 'ridge': [{'threshold_bp': 0.0,
            'max_positions': 7,
            'buy_cost_bp': 1.0,
            'sell_cost_bp': 1.0},
           {'threshold_bp': 22.0,
            'max_positions': 4,
            'buy_cost_bp': 3.0,
            'sell_cost_bp': 3.0},
           {'threshold_bp': 26.0,
            'max_positions': 2,
            'buy_cost_bp': 5.0,
            'sell_cost_bp': 5.0}],
 'catboost': [{'threshold_bp': 0.0,
               'max_positions': 50,
               'buy_cost_bp': 1.0,
               'sell_cost_bp': 1.0},
              {'threshold_bp': 1.0,
               'max_positions': 7,
               'buy_cost_bp': 3.0,
               'sell_cost_bp': 3.0},
              {'threshold_bp': 28.0,
               'max_positions': 6,
               'buy_cost_bp': 5.0,
               'sell_cost_bp': 5.0}],
 'random_forest': [{'threshold_bp': 0.0,
                    'max_positions': 11,
                    'buy_cost_bp': 1.0,
                    'sell_cost_bp': 1.0},
                   {'threshold_bp': 8.0,
                    'max_positions': 7,
                    'buy_cost_bp': 3.0,
                    'sell_cost_bp': 3.0},
                   {'threshold_bp': 16.0,
                    'max_positions': 5,
                    'buy_cost_bp': 5.0,
                    'sell_cost_bp': 5.0}],
 'decision_tree': [{'threshold_bp': 0.0,
                    'max_positions': 10,
                    'buy_cost_bp': 1.0,
                    'sell_cost_bp': 1.0},
                   {'threshold_bp': 8.0,
                    'max_positions': 5,
                    'buy_cost_bp': 3.0,
                    'sell_cost_bp': 3.0},
                   {'threshold_bp': 32.0,
                    'max_positions': 3,
                    'buy_cost_bp': 5.0,
                    'sell_cost_bp': 5.0}],
 'gru': [{'threshold_bp': 4.0,
          'max_positions': 11,
          'buy_cost_bp': 1.0,
          'sell_cost_bp': 1.0},
         {'threshold_bp': 30.0,
          'max_positions': 5,
          'buy_cost_bp': 3.0,
          'sell_cost_bp': 3.0},
         {'threshold_bp': 45.0,
          'max_positions': 1,
          'buy_cost_bp': 5.0,
          'sell_cost_bp': 5.0}],
 'lstm': [{'threshold_bp': 0.0,
           'max_positions': 10,
           'buy_cost_bp': 1.0,
           'sell_cost_bp': 1.0},
          {'threshold_bp': 18.0,
           'max_positions': 5,
           'buy_cost_bp': 3.0,
           'sell_cost_bp': 3.0},
          {'threshold_bp': 45.0,
           'max_positions': 1,
           'buy_cost_bp': 5.0,
           'sell_cost_bp': 5.0}],
 'transformer': [{'threshold_bp': 3.0,
                  'max_positions': 15,
                  'buy_cost_bp': 1.0,
                  'sell_cost_bp': 1.0},
                 {'threshold_bp': 22.0,
                  'max_positions': 3,
                  'buy_cost_bp': 3.0,
                  'sell_cost_bp': 3.0},
                 {'threshold_bp': 55.0,
                  'max_positions': 1,
                  'buy_cost_bp': 5.0,
                  'sell_cost_bp': 5.0}],
 'tcn': [{'threshold_bp': 0.0,
          'max_positions': 12,
          'buy_cost_bp': 1.0,
          'sell_cost_bp': 1.0},
         {'threshold_bp': 8.0,
          'max_positions': 7,
          'buy_cost_bp': 3.0,
          'sell_cost_bp': 3.0},
         {'threshold_bp': 26.0,
          'max_positions': 5,
          'buy_cost_bp': 5.0,
          'sell_cost_bp': 5.0}]}

BEST_VALIDATION_CONFIGS_BY_MODEL = VALIDATION_PARAMETER_GRIDS
